---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - wireguard-secret.yaml
  - pvcs.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - qbittorrent-deployment.yaml
  - qbittorrent-service.yaml
  - networkpolicy.yaml
  - istio-gateway.yaml
  - istio-virtualservice.yaml
