---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - wireguard-secret.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - qbittorrent-deployment.yaml
  - qbittorrent-service.yaml
  - debrid-media-manager-deployment.yaml
  - debrid-media-manager-service.yaml
  - networkpolicy.yaml
  - istio-gateway.yaml
  - istio-virtualservice.yaml
