---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-gateway-controller
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: cloudflare-gateway
  sourceRef:
    kind: GitRepository
    name: cloudflare-kubernetes-gateway
  path: ./config/default
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: configs
