---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: cloudflare-gateway
spec:
  gatewayClassName: cloudflare
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    hostname: "*.gluk0.sh"
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTP
    port: 80
    name: http-apex
    hostname: "gluk0.sh"
    allowedRoutes:
      namespaces:
        from: All
