---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: homelab-gateway
spec:
  controllerName: gateway-api.io/gateway-controller
---
# Basic local gateway
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: homelab-gateway
#   namespace: gateway-system  
# spec:
#   gatewayClassName: homelab-gateway
#   listeners:
#     - name: http
#       protocol: HTTP
#       port: 80
#     - name: https
#       protocol: HTTPS
#       port: 443
#       tls:
#         mode: Terminate
#         certificateRefs:
#           - kind: Secret
#             name: gateway-tls
